import esbuild from 'esbuild'
import { builtinModules } from 'node:module'
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import esbuildSvelte from 'esbuild-svelte'
import sveltePreprocess from 'svelte-preprocess'

const production = process.argv[2] === 'production'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/Andrewkfb/obsidian-mission-control
*/`

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	minify: production,
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	plugins: [
		esbuildSvelte({
			compilerOptions: {
				// Component styles ship in styles.css rather than being injected
				// from JS at runtime, so users can override them with a CSS
				// snippet — which is what Obsidian's plugin guidelines expect.
				css: 'external',
				// Every component is on runes. Opting in globally makes the
				// compiler reject legacy syntax rather than silently accepting
				// it in compatibility mode.
				runes: true,
			},
			preprocess: sveltePreprocess(),
		}),
		{
			// esbuild emits the extracted component CSS as main.css. Fold it into
			// styles.css behind the hand-written base styles, which is the file
			// Obsidian loads and the release workflow ships.
			name: 'bundle-styles',
			setup(build) {
				build.onEnd(() => {
					const base = readFileSync('src/styles.css', 'utf8')
					const components = existsSync('main.css') ? readFileSync('main.css', 'utf8') : ''
					writeFileSync('styles.css', `${base}\n${components}`)
					if (existsSync('main.css')) rmSync('main.css')
				})
			},
		},
	],
})

if (production) {
	await context.rebuild()
	await context.dispose()
} else {
	await context.watch()
}
