import esbuild from 'esbuild'
import { builtinModules } from 'node:module'
import { copyFileSync } from 'node:fs'
import esbuildSvelte from 'esbuild-svelte'
import sveltePreprocess from 'svelte-preprocess'

const production = process.argv[2] === 'production'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/Andrewkfb/obsidian-mission-control
*/`

copyFileSync('src/styles.css', 'styles.css')

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	minify: production,
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	plugins: [
		esbuildSvelte({
			compilerOptions: {
				css: 'injected',
			},
			preprocess: sveltePreprocess(),
		}),
	],
})

if (production) {
	await context.rebuild()
	await context.dispose()
} else {
	await context.watch()
}
